<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>exo 8</title>
</head>

<body>
    <h1>exercice 8</h1>
    <p>Traduire ce code avec des if et des else : ?php echo ($isOk) ? 'c'est ok !!' : 'c'est pas bon !!!'; ?></p>

    <?php

$isOk = true;

if ($isOk){
    echo 'c\'est ok !!';
}else{
    echo 'c\'est pas bon !!!';
}

?>

</body>

</html>