<!DOCTYPE html>
<html lang="fr">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>exo 7</title>
</head>

<body>
    <h1>exercice 7</h1>
    <p>Traduire ce code avec des if et des else :  ?phpecho ($isOk == false) ? 'c\'est pas bon !!!' : 'c\'est ok !!'; ?></p>

    <?php

$isOk = false;

if ($isOk){
    echo 'c\'est pas bon !!!';
}else{
    echo 'c\'est ok !!';
}

?>

</body>

</html>